version: "3.1"

services:
  pgAdmin:
    restart: always
    build:
      context: ./pgadmin
      dockerfile: ./Dockerfile
    image: demo_pgadmin4
    container_name: "demo-pgadmin"
    ports:
      - "8000:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: 1234@admin.com
      PGADMIN_DEFAULT_PASSWORD: 1234
#    volumes:
#      - ./volumes/pgadmin:/var/lib/pgadmin
    networks:
      - localnet

  postgres:
      restart: always
      build:
        context: ./postgres
        dockerfile: ./Dockerfile
      image: demo_postgres
      container_name: "demo-postgres"
      ports:
        - "5432:5432"
      environment:
        POSTGRES_USER: pg
        POSTGRES_PASSWORD: pass134
        POSTGRES_DB: testDB
#      volumes:
#        - ./volumes/pgvol:/var/lib/postgresql/data
      networks:
        - localnet
  nifi:
    build:
      context: ./nifi
      dockerfile: ./Dockerfile
    image: demo/nifi
    container_name: demo_nifi
    ports:
      - "8080:8080"
    volumes:
      - ./volumes/import:/opt/nifi/uploads
    networks:
      - localnet

  jupyter:
    build:
      context: ./jupyter
      dockerfile: ./Dockerfile
    image: demo/jupyter
    volumes:
      - ./notebooks:/home/jovyan/work
      - ./volumes/import:/home/jovyan/work/result
    environment:
      JUPYTER_ENABLE_LAB: "yes"
      JUPYTER_TOKEN: "demo123"
    ports:
      - "8888:8888"
    container_name: demo_jupyter
    networks:
      - localnet

networks:
  localnet:
    attachable: true

